### ISSUE TITLE
Voices do not play in the game.

### ISSUE THREAD

**Issue by Karitama** [Silvris/RingingBloom#3]
I used this tool to edit the MHRise type14 voices, but not all the voices played in the game. I tried importing the pck with this tool and outputting it without editing, but the voices still did not play. Is there any way to solve this problem? I wrote this using DeepL, so there may be some oddities.

**Comment by Silvris** [comment]
What all files did you include with the edit? It's possible that some header information changed from the export (likely so, since I don't remember when I fixed all of that), so you have to remember to include both the proper pck (streaming/Sound/WWise) and the nonstream pck (Sound/WWise).

**Comment by Karitama** [comment]
Thanks for the reply. I have edited STM\streaming\Sound\Wwise\pl_voice_f_14_media.pck.3.X64.Ja with this tool. I moved the pck file to my desktop, edited it, and placed the two output files in the designated locations in my own mod folder. I placed the .pck file in STM\streaming\Sound\Wwise. The .notstream file, of course, I erased the .notstream at the end of the file and placed it in STM\Sound\Wwise.

**Comment by Karitama** [comment]
I still can't succeed. I have followed the steps, but the voice is not playing. Is there another file that I need to edit? Or am I using the tool incorrectly? Is this tool not available for the PC version?

**Comment by srwseki** [comment]
> What all files did you include with the edit? It's possible that some header information changed from the export (likely so, since I don't remember when I fixed all of that), so you have to remember to include both the proper pck (streaming/Sound/WWise) and the nonstream pck (Sound/WWise).

Hi Silvris, thanks for your tool, it's very helpful. I'm using RingingBloom to mod 'The King of Fighter XV' music, it works perfectly to extract wem from pck file, but when it replaces wem files in pck, it drops all the bnk files in pck, and then the game doesn't play music in the modified pck. Would you please add support to keep bnk files inside pck? my email is srseki@gmail.com
